tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/core"
brew "aspell"
brew "buildkit"
brew "dos2unix"
brew "gh"
brew "git"
brew "python@3.9"
brew "helm", link: false
brew "libvirt"
brew "python@3.10"
brew "python@3.8"
brew "qemu"
brew "socat"
brew "telnet"
brew "terraform"
brew "heroku/brew/heroku"
cask "logitech-camera-settings"
cask "ngrok"
cask "obs", args: { appdir: "/Applications" }
cask "postman", args: { appdir: "/Applications" }
cask "rancher"
cask "vagrant", args: { appdir: "/Applications" }
cask "visual-studio-code", args: { appdir: "/Applications" }
cask "wireshark"
